import { batches, challenges, userChallenges, users } from "./config/schema";
import { BatchStatus, BatchUserStatus, ChallengeId, ReviewAction, UserRole } from "./config/types";

export const SEED_DATA_VERSION = "1.1.2";

// Using Drizzle's inferred insert types to ensure seed data
// matches database schema requirements
export const seedUsers: (typeof users.$inferInsert)[] = [
  {
    userAddress: "0xB4F53bd85c00EF22946d24Ae26BC38Ac64F5E7B1",
    role: UserRole.USER,
    createdAt: new Date(1679063274534),
    socialX: "pabl0cks",
    socialTelegram: "pabl0cks",
    batchStatus: BatchUserStatus.GRADUATE,
  },
  {
    userAddress: "0x000084821704d731438d2D06f4295e1AB0ace7D8",
    role: UserRole.USER,
    createdAt: new Date(1664777161512),
    socialEmail: "ryuufarhan7@gmail.com",
    socialX: "FarhanRyuu",
    batchStatus: BatchUserStatus.CANDIDATE,
  },
  {
    userAddress: "0x014EC6296B3493f0f59a3FE90E0FFf377fb8826a",
    role: UserRole.USER,
    createdAt: new Date(1672731143934),
    socialEmail: "gokulkesavan5005@gmail.com",
    socialX: "meta_Goku",
    socialGithub: "kesgokul",
    batchStatus: BatchUserStatus.CANDIDATE,
  },
  {
    userAddress: "0x01B2686Bd146bFc3F4B3DD6F7F86f26ac7c2f7Fd",
    role: UserRole.USER,
    createdAt: new Date(1668050419502),
    socialEmail: "afo@wefa.app",
    socialX: "Time_Is_Oba",
    socialGithub: "Oba-One",
    batchStatus: BatchUserStatus.CANDIDATE,
  },
  {
    userAddress: "0x45334F41aAA464528CD5bc0F582acadC49Eb0Cd1",
    role: UserRole.USER,
    createdAt: new Date(1679063274534),
    socialX: "rinat_eth",
    socialTelegram: "rinat_eth",
  },
];

export const seedChallenges: (typeof challenges.$inferInsert)[] = [
  {
    id: ChallengeId.SIMPLE_COUNTER_EXAMPLE,
    challengeName: "🎟 Simple Counter Example",
    github: "abhi152003/speedrun_stylus:counter",
    autograding: false,
    description:
      "🎫 Create a simple Counter to learn the basics of 🏗 scaffold-eth with RUST. You'll use 👷‍♀️ Stylus Nitro Devnode to compile and deploy your smart contracts. Then, you'll use a template React app filled with essential components and hooks. Finally, you'll deploy your Counter Contract to a public network to share with friends! 🚀",
    sortOrder: 0,
    previewImage: "/assets/challenges/counter.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.SIMPLE_NFT_EXAMPLE,
    challengeName: "🖼️ Simple NFT Example",
    github: "abhi152003/speedrun_stylus:nft",
    autograding: false,
    description:
      "Dive into creating an NFT project to master the essentials of 🛠 scaffold-eth with RUST. Use 💻 Stylus Nitro Devnode to design, compile, and deploy smart contracts that bring NFTs to life. Pair your work with a dynamic React app featuring all the tools 🧩. Wrap it up by deploying your NFT contract to a public network, where users can mint 🎟, verify 🔍, and manage their NFTs effortlessly! 🌐",
    sortOrder: 1,
    previewImage: "/assets/challenges/simpleNFT.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.VENDING_MACHINE,
    challengeName: "🏵 Vending Machine",
    github: "abhi152003/speedrun_stylus:vending-machine",
    autograding: false,
    description:
      "🤖 Vending machines meet blockchain! Let's create a decentralized cupcake dispenser powered by a smart contract. Users can claim cupcakes (digital rewards) at intervals and track their balances on-chain. Learn how time-based access and contract-to-user interactions work seamlessly with Rust and Stylus. 🍰 Sweet, unstoppable, and fun!",
    sortOrder: 2,
    previewImage: "/assets/challenges/tokenVendor.svg",
    dependencies: [],
    icon: "/assets/key_icon.svg",
  },
  {
    id: ChallengeId.MULTISIG_WALLET,
    challengeName: "🎲 Multisig Wallet",
    github: "abhi152003/speedrun_stylus:multi-sig",
    autograding: false,
    description:
      "👩‍👩‍👧‍👧 A multi-signature smart contract secures assets by requiring multiple owners to confirm transactions before execution. Transactions are tracked in an array of TxStruct objects, and owners can submit, confirm, or revoke confirmations. A transaction is executed once it reaches the required number of confirmations, ensuring that no single owner can act alone, providing enhanced security for the assets.",
    sortOrder: 3,
    previewImage: "/assets/challenges/multiSig.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.UNISWAP_V2_STYLUS,
    challengeName: "⚖️ Uniswap-V2",
    github: "abhi152003/speedrun_stylus:stylus-uniswap",
    autograding: false,
    description:
      "🔄 Uniswap V2! Build a Uniswap V2-style liquidity pool interface with smart contracts for token pair initialization, liquidity management, and token swaps. Utilize Arbitrum Stylus Nitro to deploy contracts, handle liquidity operations like minting and burning, and facilitate seamless token transfers with allowance management. Create an intuitive Next.js frontend to interact with the pool. Deploy your app to Vercel to provide users with a robust and accessible DeFi experience! 🚀",
    sortOrder: 4,
    previewImage: "/assets/challenges/dex.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.BUIDL_GUIDL,
    challengeName: "Eligible to join 🏰️ BuidlGuidl",
    github: "",
    autograding: false,
    description:
      "The Arbitrum Stylus Collective is a hub for innovative builders leveraging Stylus to push the boundaries of Web3. A space to showcase your Rust and Solidity creations, connect with fellow developers, and grow the ecosystem.",
    sortOrder: 5,
    previewImage: "/assets/bg.svg",
    dependencies: [],
    icon: "/assets/vault_icon.svg",
    externalLink: {
      link: "https://buidlguidl.com/",
      claim: "Join the 🏰️ BuidlGuidl",
    },
  },
  {
    id: ChallengeId.ZKP_AGE,
    challengeName: "👶 ZKP - Age Verifier",
    github: "abhi152003/speedrun_stylus:stylus-zkp-age-verifier",
    autograding: false,
    description:
      "Build a privacy-preserving age verification system using Zero-Knowledge Proofs! Prove users are above a certain age (e.g., 18+) without revealing their exact birthdate or identity. Leverage ZK circuits to validate age data and integrate it into a slick Next.js frontend. Deploy on Arbitrum Stylus Nitro for lightning-fast proofs and privacy at scale. Wrap it up with a Vercel deployment for smooth, trustless age-gating in any app or platform!👶🛡️",
    sortOrder: 6,
    previewImage: "/assets/challenges/age.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.ZKP_BALANCE,
    challengeName: "💰 ZKP - Balance Checker",
    github: "abhi152003/speedrun_stylus:stylus-zkp-balance-checker",
    autograding: false,
    description:
      "🔐 Design a secure system that proves a user has a minimum token balance—without exposing the exact amount! Using ZKPs, generate proofs that validate wallet holdings above a threshold. Pair your smart contract logic on Arbitrum Stylus with a clean frontend that lets users verify balances privately. Great for token-gated access, whitelists, or DeFi participation. Ship it via Vercel for instant, privacy-first access. 🧮🔍",
    sortOrder: 7,
    previewImage: "/assets/challenges/balance.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.ZKP_PASSWORD,
    challengeName: "🔑 ZKP - Password Verifier",
    github: "abhi152003/speedrun_stylus:stylus-zkp-password-verifier",
    autograding: false,
    description:
      "🔑No more password sharing! Build a password verifier that confirms knowledge of a password without revealing it. Use ZK-SNARKs to create proof-of-knowledge circuits, deploy them on Arbitrum Stylus, and build a secure frontend to generate and verify proofs. Perfect for login systems, secret validation, or private voting. Launch on Vercel to deliver fast, trustless password validation. 🧠🔒🔑",
    sortOrder: 8,
    previewImage: "/assets/challenges/password.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.ZKP_LOCATION,
    challengeName: "📍 ZKP - Location Verifier",
    github: "abhi152003/speedrun_stylus:stylus-zkp-location-verifier",
    autograding: false,
    description:
      "📍 Prove you're in the right place—without revealing your location! Use Zero-Knowledge Proofs to create a location-based verifier app. Generate proofs that confirm geographic conditions (e.g., within a city or country) while keeping coordinates private. Deploy smart contracts on Arbitrum Stylus and build a map-friendly frontend with location privacy baked in. Perfect for geo-restricted content, voting, or access control. 🌍🛰️",
    sortOrder: 9,
    previewImage: "/assets/challenges/location.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.ZKP_MODEL,
    challengeName: "📊 ZKP - Model Verifier",
    github: "abhi152003/speedrun_stylus:stylus-zkp-model-verifier",
    autograding: false,
    description:
      "Prove your AI model meets required benchmarks or is built a certain way—without revealing the model itself! Use ZKPs to validate model accuracy, structure, or source on-chain. Deploy verification contracts via Arbitrum Stylus, build a frontend for model creators and consumers, and use Vercel for streamlined app delivery. Ideal for AI marketplaces, provable research, or secure collaboration. 🧠🧾",
    sortOrder: 10,
    previewImage: "/assets/challenges/model.svg",
    dependencies: [],
  },
  {
    id: ChallengeId.ZK_EMAIL_VERIFIER,
    challengeName: "📧 ZKP - Email Domain Verifier",
    github: "",
    autograding: false,
    description:
      "Build an app that verifies users own an email with a specific domain—without revealing the full address. Use ZKPs to prove domain membership (e.g., @university.edu) while keeping the full identity private. Arbitrum Stylus handles smart contract verification, and a frontend built with Next.js enables easy interactions. Deploy on Vercel for domain-gated access with bulletproof privacy. ✅📬",
    sortOrder: 11,
    previewImage: "/assets/challenges/email.svg",
    dependencies: [],
    disabled: true,
  },
];

export const seedUserChallenges: (typeof userChallenges.$inferInsert)[] = [
  {
    userAddress: seedUsers?.[0]?.userAddress,
    challengeId: ChallengeId.SIMPLE_NFT_EXAMPLE,
    frontendUrl: "https://dreary-use.surge.sh/",
    contractUrl: "https://sepolia.etherscan.io/address/0x7f918d7b7d0fe0d3a8de3c0570ed4e154c0096e0",
    reviewComment: "Dummy review, nice work",
    submittedAt: new Date(1679063312936),
    reviewAction: ReviewAction.ACCEPTED,
    signature:
      "0x7a808ee181d8655f38c48e0154903bea229b91e32f6062f6c23ad9da5fa25c3008238b07e367e7904200015157a43378b39244140c43ea35e5eea11c055a170500",
  },
  {
    userAddress: seedUsers?.[0]?.userAddress,
    challengeId: ChallengeId.SIMPLE_COUNTER_EXAMPLE,
    frontendUrl: "https://aggressive-party.surge.sh/",
    contractUrl: "https://sepolia.etherscan.io/address/0xd08b984c3ee4a880112d81de5a4a074c857b7f2f",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1679359244796),
    reviewAction: ReviewAction.ACCEPTED,
    signature:
      "0x4eca15955283c15c1f9565945c34638c9943a313a79301d73178b814e82e3e183e3d89aebdafa10a1012912cb820950fb6eea6ba76e58bf875f226bdc8257dc700",
  },
  {
    userAddress: seedUsers?.[0]?.userAddress,
    challengeId: ChallengeId.VENDING_MACHINE,
    frontendUrl: "https://chunky-beam.surge.sh/",
    contractUrl: "https://sepolia.etherscan.io/address/0xbF35fC995A2Cc4F1508B5F769922623dE7f220d6",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1679185806311),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[0]?.userAddress,
    challengeId: ChallengeId.MULTISIG_WALLET,
    frontendUrl: "https://nonstop-fiction.surge.sh/",
    contractUrl: "https://sepolia.etherscan.io/address/0x57D312c3E4bF22F22d6A900Be8B38b5546b47C3f",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1679317471852),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[1]?.userAddress,
    challengeId: ChallengeId.SIMPLE_NFT_EXAMPLE,
    frontendUrl: "http://simple-nft-ryuufarhan.surge.sh/",
    contractUrl: "https://goerli.etherscan.io/address/0x861346d67b728949bcb69595638a78723a2adae3",
    reviewComment: "Dummy review, nice work",
    submittedAt: new Date(1664778633262),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[1]?.userAddress,
    challengeId: ChallengeId.SIMPLE_NFT_EXAMPLE,
    frontendUrl: "http://clumsy-week.surge.sh",
    contractUrl: "https://goerli.etherscan.io/address/0xe3DF14f1482074916A8Aeb40d84898C879b2B5f6",
    reviewComment: "Dummy review, nice work",
    submittedAt: new Date(1672831270556),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[2]?.userAddress,
    challengeId: ChallengeId.VENDING_MACHINE,
    frontendUrl: "https://busy-pizzas.surge.sh",
    contractUrl: "https://goerli.etherscan.io/address/0xEd2aF24B1a657000C9b4509BC91FCfA5E76D3d33",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1672974794575),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[2]?.userAddress,
    challengeId: ChallengeId.MULTISIG_WALLET,
    frontendUrl: "https://tasteful-plough.surge.sh",
    contractUrl: "https://goerli.etherscan.io/address/0xf3384118b56827271979A879e2d5A4d28569eb48",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1672830084301),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[2]?.userAddress,
    challengeId: ChallengeId.UNISWAP_V2_STYLUS,
    frontendUrl: "https://sour-snake.surge.sh",
    contractUrl: "https://goerli.etherscan.io/address/0x0752d3847601b506cBFB10330172821B495e6bB0",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1673006384070),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[2]?.userAddress,
    challengeId: ChallengeId.BUIDL_GUIDL,
    frontendUrl: "https://speedrunethereum.com/challenge/token-vendor",
    contractUrl: "https://goerli.etherscan.io/address/0x9626C68Dd8d000BBB7B06f0782266976dEB91c35",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1672819901984),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[3]?.userAddress,
    challengeId: ChallengeId.SIMPLE_NFT_EXAMPLE,
    frontendUrl: "https://kind-fifth.surge.sh/",
    contractUrl: "https://goerli.etherscan.io/address/0xb9487f8d9E336a9468fcbb50dAF39587D0EBCA63",
    reviewComment: "Dummy review, nice work",
    submittedAt: new Date(1668196973527),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[3]?.userAddress,
    challengeId: ChallengeId.ZKP_AGE,
    frontendUrl: "https://stupid-beginner.surge.sh",
    contractUrl: "https://goerli.etherscan.io/address/0xd68edd04EbB81c6f187A526F3656C18dD0258cd8",
    reviewComment: "Dummy review, it's working great",
    submittedAt: new Date(1668830120864),
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[4]?.userAddress,
    challengeId: ChallengeId.ZKP_BALANCE,
    frontendUrl: "https://sepolia-optimism.etherscan.io/address/0xad5e878a62D5B77277aCDC321614a9727815B4C8#code",
    contractUrl: "https://sepolia-optimism.etherscan.io/address/0xad5e878a62D5B77277aCDC321614a9727815B4C8#code",
    submittedAt: new Date(1736441361988),
    reviewComment:
      "<p>You have successfully passed challenge 2!</p><p>You have passed the first three challenges on SpeedRunEthereum and can now join the BuidlGuidl!</p>",
    reviewAction: ReviewAction.REJECTED,
  },
  {
    userAddress: seedUsers?.[4]?.userAddress,
    challengeId: ChallengeId.SIMPLE_NFT_EXAMPLE,
    frontendUrl: "https://sepolia-optimism.etherscan.io/address/0x82b4935ebe7a5d802cf465a3495da1aff96f1153#code",
    contractUrl: "https://sepolia-optimism.etherscan.io/address/0x82b4935ebe7a5d802cf465a3495da1aff96f1153#code",
    submittedAt: new Date(1736437841322),
    reviewComment: "<p>You passed all tests on Challenge 0, keep it up!</p>",
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[4]?.userAddress,
    challengeId: ChallengeId.ZKP_PASSWORD,
    frontendUrl: "https://sepolia-optimism.etherscan.io/address/0x75CCfC494667c91F4926213A04619f93812885b2#code",
    contractUrl: "https://sepolia-optimism.etherscan.io/address/0x75CCfC494667c91F4926213A04619f93812885b2#code",
    submittedAt: new Date(1736440199150),
    reviewComment: "<p>You passed all tests on Challenge 1, keep it up!</p>",
    reviewAction: ReviewAction.SUBMITTED,
  },
  {
    userAddress: seedUsers?.[4]?.userAddress,
    challengeId: ChallengeId.ZKP_LOCATION,
    frontendUrl: "https://sepolia-optimism.etherscan.io/address/0xB30b4D0AD811De445656FA49d3CbfD26f24Fa20f#code",
    contractUrl: "https://sepolia-optimism.etherscan.io/address/0xB30b4D0AD811De445656FA49d3CbfD26f24Fa20f#code",
    submittedAt: new Date(1736455465938),
    reviewComment:
      "<p>This looks good! Demo site and contract code are solid and the dice only roll when it's a winner!</p>",
    reviewAction: ReviewAction.ACCEPTED,
  },
  {
    userAddress: seedUsers?.[4]?.userAddress,
    challengeId: ChallengeId.ZKP_MODEL,
    frontendUrl: "https://sepolia-optimism.etherscan.io/address/0xFD893C93f44fdCd16D4673072D2a071578e6C7Ee#code",
    contractUrl: "https://sepolia-optimism.etherscan.io/address/0xFD893C93f44fdCd16D4673072D2a071578e6C7Ee#code",
    submittedAt: new Date(1736523426599),
    reviewComment: "<p>You have successfully passed the Dex Challenge! Great work!</p>",
    reviewAction: ReviewAction.ACCEPTED,
  },
];

// userAddresses denotes the user addresses that will be added to the batch
export const seedBatches: (typeof batches.$inferInsert & { userAddresses?: string[] })[] = [
  {
    name: "Batch 1",
    startDate: new Date(1705315180000),
    status: BatchStatus.CLOSED,
    telegramLink: "https://t.me/joinchat/1",
    contractAddress: "0x0000000000000000000000000000000000000000",
    bgSubdomain: "batch1",
    userAddresses: [seedUsers?.[0]?.userAddress, seedUsers?.[1]?.userAddress],
  },
  {
    name: "Batch 2",
    startDate: new Date(1707820780000),
    status: BatchStatus.CLOSED,
    telegramLink: "https://t.me/joinchat/2",
    contractAddress: "0x0000000000000000000000000000000000000000",
    bgSubdomain: "batch2",
    userAddresses: [seedUsers?.[2]?.userAddress, seedUsers?.[3]?.userAddress],
  },
  {
    name: "Batch 3",
    startDate: new Date(1705315180000),
    status: BatchStatus.OPEN,
    telegramLink: "https://t.me/joinchat/3",
    contractAddress: "0x0000000000000000000000000000000000000000",
    bgSubdomain: "batch3",
  },
];
