/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#088484",
          "primary-content": "#ffffff",
          secondary: "#C8F5FF",
          "secondary-content": "#026262",
          accent: "#67DDDE",
          "accent-content": "#026262",
          neutral: "#1A202C",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#E9FBFF",
          "base-300": "#C8F5FF",
          "base-content": "#026262",
          info: "#2FBABB",
          success: "#C8F5FF",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#C8F5FF",
          "primary-content": "#000000",
          secondary: "#026262",
          "secondary-content": "#C8F5FF",
          accent: "#67DDDE",
          "accent-content": "#C8F5FF",
          neutral: "#CBD5E0",
          "neutral-content": "#088484",
          "base-100": "#088484",
          "base-200": "#026262",
          "base-300": "#088484",
          "base-content": "#C8F5FF",
          info: "#67DDDE",
          success: "#22797b",
          warning: "#717326",
          error: "#6e2a2a",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
